ERROR 2025-10-04 16:33:58,027 log 265245 128843845203520 Internal Server Error: /
Traceback (most recent call last):
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'djdt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/debug_toolbar/middleware.py", line 74, in __call__
    rendered = toolbar.render_toolbar()
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/debug_toolbar/toolbar.py", line 82, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace
ERROR 2025-10-04 16:33:58,028 basehttp 265245 128843845203520 "GET / HTTP/1.1" 500 151010
ERROR 2025-10-04 16:34:20,411 log 265245 128843845203520 Internal Server Error: /
Traceback (most recent call last):
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'djdt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/debug_toolbar/middleware.py", line 74, in __call__
    rendered = toolbar.render_toolbar()
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/debug_toolbar/toolbar.py", line 82, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace
ERROR 2025-10-04 16:34:20,411 basehttp 265245 128843845203520 "GET / HTTP/1.1" 500 151010
ERROR 2025-10-04 16:34:49,175 log 265245 128843845203520 Internal Server Error: /
Traceback (most recent call last):
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'djdt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/debug_toolbar/middleware.py", line 74, in __call__
    rendered = toolbar.render_toolbar()
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/debug_toolbar/toolbar.py", line 82, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace
ERROR 2025-10-04 16:34:49,176 basehttp 265245 128843845203520 "GET / HTTP/1.1" 500 151010
INFO 2025-10-04 17:08:19,463 autoreload 292351 137429404377088 Watching for file changes with StatReloader
INFO 2025-10-04 17:14:03,066 autoreload 300167 139551144554496 Watching for file changes with StatReloader
ERROR 2025-10-04 17:14:17,863 log 300413 135006389084160 Internal Server Error: /api/v1/chatbots/
Traceback (most recent call last):
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/rest_framework/views.py", line 333, in check_permissions
    self.permission_denied(
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/rest_framework/views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/rest_framework/settings.py", line 177, in import_from_string
    return import_string(val)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'apps.core.exceptions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/rest_framework/views.py", line 463, in handle_exception
    exception_handler = self.get_exception_handler()
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/rest_framework/views.py", line 298, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/rest_framework/settings.py", line 225, in __getattr__
    val = perform_import(val, attr)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/rest_framework/settings.py", line 166, in perform_import
    return import_from_string(val, setting_name)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/rest_framework/settings.py", line 180, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'apps.core.exceptions.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'apps.core.exceptions'.
ERROR 2025-10-04 17:14:17,944 log 300413 135006389084160 Internal Server Error: /api/v1/chatbots/
Traceback (most recent call last):
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
TypeError: 'TemplatesPanel' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'djdt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/debug_toolbar/middleware.py", line 74, in __call__
    rendered = toolbar.render_toolbar()
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/debug_toolbar/toolbar.py", line 82, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 208, in render
    return template.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 715, in resolve
    obj = self.var.resolve(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/debug_toolbar/panels/__init__.py", line 103, in content
    return render_to_string(self.template, self.get_stats())
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace
ERROR 2025-10-04 17:14:58,138 log 301120 132908768313344 Internal Server Error: /api/v1/chatbots/
Traceback (most recent call last):
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django_redis/cache.py", line 29, in _decorator
    return method(self, *args, **kwargs)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django_redis/cache.py", line 99, in _get
    return self.client.get(key, default=default, version=version, client=client)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django_redis/client/default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/rest_framework/views.py", line 416, in initial
    self.check_throttles(request)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/rest_framework/views.py", line 359, in check_throttles
    if not throttle.allow_request(request, self):
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/rest_framework/throttling.py", line 123, in allow_request
    self.history = self.cache.get(self.key, [])
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django_redis/cache.py", line 92, in get
    value = self._get(key, default, version, client)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django_redis/cache.py", line 36, in _decorator
    raise e.__cause__
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django_redis/client/default.py", line 258, in get
    value = client.get(key)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/redis/commands/core.py", line 1829, in get
    return self.execute_command("GET", name)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/redis/client.py", line 533, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/redis/connection.py", line 1086, in get_connection
    connection.connect()
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/redis/connection.py", line 270, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
INFO 2025-10-04 17:16:34,656 autoreload 302725 125965150134272 Watching for file changes with StatReloader
INFO 2025-10-04 17:16:44,941 autoreload 302888 135139487092736 Watching for file changes with StatReloader
ERROR 2025-10-04 17:18:50,249 log 265245 128843845203520 Internal Server Error: /
Traceback (most recent call last):
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'djdt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/debug_toolbar/middleware.py", line 74, in __call__
    rendered = toolbar.render_toolbar()
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/debug_toolbar/toolbar.py", line 82, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace
ERROR 2025-10-04 17:18:50,250 basehttp 265245 128843845203520 "GET / HTTP/1.1" 500 151010
ERROR 2025-10-04 17:18:56,510 log 265245 128843845203520 Internal Server Error: /health/
Traceback (most recent call last):
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'djdt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/debug_toolbar/middleware.py", line 74, in __call__
    rendered = toolbar.render_toolbar()
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/debug_toolbar/toolbar.py", line 82, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/sakr_quraish/Projects/Ismail/venv/lib/python3.10/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace
ERROR 2025-10-04 17:18:56,510 basehttp 265245 128843845203520 "GET /health/ HTTP/1.1" 500 151078
INFO 2025-10-04 17:19:25,672 basehttp 305264 124407326438976 "GET / HTTP/1.1" 200 83
INFO 2025-10-04 17:19:29,800 basehttp 305264 124407326438976 "GET /health/ HTTP/1.1" 200 16
INFO 2025-10-04 17:19:34,781 basehttp 305264 124407326438976 "GET /api/v1/health/ HTTP/1.1" 200 16
WARNING 2025-10-05 10:06:19,062 log 483227 135018940724800 Not Found: /api/health/
WARNING 2025-10-05 10:06:19,063 basehttp 483227 135018940724800 "GET /api/health/ HTTP/1.1" 404 2816
INFO 2025-10-05 10:06:23,947 basehttp 483227 135018940724800 "GET /api/v1/health/ HTTP/1.1" 200 16
ERROR 2025-10-05 10:06:30,569 log 483227 135018940724800 Internal Server Error: /api/v1/auth/register/
ERROR 2025-10-05 10:06:30,569 basehttp 483227 135018940724800 "POST /api/v1/auth/register/ HTTP/1.1" 500 65
ERROR 2025-10-05 10:06:47,492 log 483227 135018940724800 Internal Server Error: /api/v1/auth/register/
ERROR 2025-10-05 10:06:47,492 basehttp 483227 135018940724800 "POST /api/v1/auth/register/ HTTP/1.1" 500 65
ERROR 2025-10-05 10:07:26,214 log 483227 135018940724800 Internal Server Error: /api/v1/auth/register/
ERROR 2025-10-05 10:07:26,214 basehttp 483227 135018940724800 "POST /api/v1/auth/register/ HTTP/1.1" 500 65
INFO 2025-10-05 10:07:56,867 basehttp 484869 130762653300288 "POST /api/v1/auth/register/ HTTP/1.1" 201 954
WARNING 2025-10-05 10:08:09,587 log 484869 130762653300288 Unauthorized: /api/v1/auth/login/
WARNING 2025-10-05 10:08:09,588 basehttp 484869 130762653300288 "POST /api/v1/auth/login/ HTTP/1.1" 401 74
WARNING 2025-10-05 10:08:29,415 log 484869 130762653300288 Unauthorized: /api/v1/auth/login/
WARNING 2025-10-05 10:08:29,415 basehttp 484869 130762653300288 "POST /api/v1/auth/login/ HTTP/1.1" 401 74
WARNING 2025-10-05 10:09:04,049 log 484869 130762653300288 Unauthorized: /api/v1/auth/login/
WARNING 2025-10-05 10:09:04,049 basehttp 484869 130762653300288 "POST /api/v1/auth/login/ HTTP/1.1" 401 74
INFO 2025-10-05 10:10:44,782 basehttp 488157 131458748380736 "GET /api/v1/health/ HTTP/1.1" 200 16
WARNING 2025-10-05 10:10:44,797 log 488157 131458739988032 Bad Request: /api/v1/auth/register/
WARNING 2025-10-05 10:10:44,798 basehttp 488157 131458739988032 "POST /api/v1/auth/register/ HTTP/1.1" 400 117
INFO 2025-10-05 10:10:57,602 basehttp 488157 131458748380736 "GET /api/v1/health/ HTTP/1.1" 200 16
INFO 2025-10-05 10:10:57,943 basehttp 488157 131458739988032 "POST /api/v1/auth/register/ HTTP/1.1" 201 969
INFO 2025-10-05 10:10:58,292 basehttp 488157 131458739988032 "POST /api/v1/auth/login/ HTTP/1.1" 200 933
INFO 2025-10-05 10:10:58,346 basehttp 488157 131458739988032 "POST /api/v1/auth/refresh/ HTTP/1.1" 200 395
WARNING 2025-10-05 10:10:58,397 log 488157 131458739988032 Unauthorized: /api/v1/auth/me/
WARNING 2025-10-05 10:10:58,398 basehttp 488157 131458739988032 "GET /api/v1/auth/me/ HTTP/1.1" 401 124
WARNING 2025-10-05 10:10:58,442 log 488157 131458739988032 Unauthorized: /api/v1/auth/me/update/
WARNING 2025-10-05 10:10:58,443 basehttp 488157 131458739988032 "PATCH /api/v1/auth/me/update/ HTTP/1.1" 401 124
WARNING 2025-10-05 10:10:58,488 log 488157 131458739988032 Bad Request: /api/v1/auth/register/
WARNING 2025-10-05 10:10:58,488 basehttp 488157 131458739988032 "POST /api/v1/auth/register/ HTTP/1.1" 400 195
WARNING 2025-10-05 10:10:58,534 log 488157 131458739988032 Unauthorized: /api/v1/auth/login/
WARNING 2025-10-05 10:10:58,534 basehttp 488157 131458739988032 "POST /api/v1/auth/login/ HTTP/1.1" 401 74
WARNING 2025-10-05 10:10:58,583 log 488157 131458739988032 Unauthorized: /api/v1/auth/logout/
WARNING 2025-10-05 10:10:58,584 basehttp 488157 131458739988032 "POST /api/v1/auth/logout/ HTTP/1.1" 401 124
WARNING 2025-10-05 10:11:06,824 log 488157 131458748380736 Not Found: /api/v1/auth/
WARNING 2025-10-05 10:11:06,824 basehttp 488157 131458748380736 "GET /api/v1/auth/ HTTP/1.1" 404 14556
INFO 2025-10-05 12:57:17,807 autoreload 661269 124477269897216 Watching for file changes with StatReloader
